### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by ingopeine** [babylonorchester/babylonorchester.github.io#2]
![bo-favicon_16px](https://user-images.githubusercontent.com/14872886/36344775-8c716840-141f-11e8-9de4-44dfe16d311f.png)
![bo-favicon_32px](https://user-images.githubusercontent.com/14872886/36344776-8c8c1b40-141f-11e8-9eea-9491525c4e3e.png)
![bo-favicon_64px](https://user-images.githubusercontent.com/14872886/36344777-8ca4cf1e-141f-11e8-8e8b-3c31a5dae526.png)

Ich bin nicht sicher, welche Du alle verwenden kann. Wenn Du noch was anderes brauchst, um das Icon transparent darzustellen, sag Bescheid!

**Comment by LeducH** [comment]
Auch hier ist das favicon schon eingebunden. ich denke es ist besser es mit einem weisen hintergrund zu belassen, da es besser zu sehen ist.
