### ISSUE TITLE
Logo graphic

### ISSUE THREAD

**Issue by ingopeine** [babylonorchester/babylonorchester.github.io#3]
![bo-headerlogo_01](https://user-images.githubusercontent.com/14872886/36344825-38e08534-1420-11e8-8631-dc0d357c08b7.png)

Bitte das Logo austauschen - die Textzeilen gehören hier mit dazu.
Die Graphic ist auf die ganze Höhe des Headers angelegt!

**Comment by LeducH** [comment]
Ich wuerde es beim alten Logo belassen. Ich denke das sieht besser aus und format ist etwas zu klein.
