### ISSUE TITLE
YouTube-Link: "Between Carthage And Rome"

### ISSUE THREAD

**Issue by babylonorchester** [babylonorchester/babylonorchester.github.io#5]
Lieber Huy,

wie geht es dir? 
Wir müssten in Kürze dringend eins von unseren neuen Videos auf der Website veröffentlichen, weshalb ich dir an dieser Stelle den Youtube-Link zu "Between Carthage and Rome" schicke:

https://www.youtube.com/watch?v=C4hg7norXQo

Wir hatte noch nicht besprochen WO GENAU es eingefügt werden soll, ich gehe aber davon aus, dass es möglichst zentral sein sollte (-vermutlich kommen in Kürze dann noch ein zwei weitere dazu).

Dürften wir dich bitten das Video einzubetten?
Das wäre wirklich super!

Einen lieben Gruß und vielen Dank im Voraus,

A.

**Comment by LeducH** [comment]
Alles klar lass mich wissen wo es hin soll und ich werde es einfuegen.
